name: dials-rest
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - dials>=3.14
  - fastapi
  - prometheus-fastapi-instrumentator
  - python=3.10
  - python-dateutil
  - python-jose
  - uvicorn[standard]
