name: dials-rest-dev
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - dials>=3.14
  - dials-data
  - fastapi
  - httpx
  - prometheus-fastapi-instrumentator
  - pytest
  - python=3.10
  - python-dateutil
  - python-jose
  - uvicorn[standard]
